name: Deploy
on:
  push:
    branches:
      - main

jobs:
  release-prod:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
